image: docker.io/golang:1.24-alpine
# image: ${DOCKER_REGISTRY}/golang:1.24-alpine

stages:
  - test
  - build
  - deploy

format:
  stage: test
  script:
    - make test

compile:
  stage: build
  script:
    - make build
  artifacts:
    paths:
      - mybinaries

deploy:
  stage: deploy
  script: echo "Define your deployment script!"
  environment: production
